In [1]:
!pip install requests
!pip install bs4
!pip install pandas

Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (2.31.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests) (2024.6.2)
Collecting bs4
  Downloading bs4-0.0.2-py2.py3-none-any.whl (1.2 kB)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.10/dist-packages (from bs4) (4.12.3)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4->bs4) (2.5)
Installing collected packages: bs4
Successfully installed bs4-0.0.2
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2023.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.25.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [2]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [3]:
url='https://en.wikipedia.org/wiki/List_of_largest_companies_in_the_United_States_by_revenue'
page=requests.get(url)
soup=BeautifulSoup(page.text,'html.parser')

In [14]:
table = soup.find_all('table')[1]

In [18]:
#soup.find('table', class_='wikitable sortable') #another way to pull our revenue table

In [34]:
world_titles=table.find_all('th')
world_titles

[<th>Rank
 </th>,
 <th>Name
 </th>,
 <th>Industry
 </th>,
 <th>Revenue <br/>(USD millions)
 </th>,
 <th>Revenue growth
 </th>,
 <th>Employees
 </th>,
 <th>Headquarters
 </th>]

In [35]:
world_table_titles=[title.text.strip() for title in world_titles]
world_table_titles

['Rank',
 'Name',
 'Industry',
 'Revenue (USD millions)',
 'Revenue growth',
 'Employees',
 'Headquarters']

In [40]:
df= pd.DataFrame(columns=world_table_titles)
df

Empty DataFrame
Columns: [Rank, Name, Industry, Revenue (USD millions), Revenue growth, Employees, Headquarters]
Index: []

In [42]:
col_data=table.find_all('tr')

In [48]:
for row in col_data[1:]:
  row_data = row.find_all('td')
  row_data=[data.text.strip() for data in row_data]
  length=len(df)
  df.loc[length]=row_data

In [49]:
print(df)

   Rank                      Name                    Industry  \
0     1                   Walmart                      Retail
1     2                    Amazon  Retail and cloud computing
2     3                ExxonMobil          Petroleum industry
3     4                     Apple        Electronics industry
4     5        UnitedHealth Group                  Healthcare
..  ...                       ...                         ...
95   96                  Best Buy                      Retail
96   97      Bristol-Myers Squibb     Pharmaceutical industry
97   98           United Airlines                     Airline
98   99  Thermo Fisher Scientific      Laboratory instruments
99  100                  Qualcomm                  Technology

   Revenue (USD millions) Revenue growth  Employees             Headquarters
0                 611,289           6.7%  2,100,000    Bentonville, Arkansas
1                 513,983           9.4%  1,540,000      Seattle, Washington
2                 413,680          44.8%     62,000            Spring, Texas
3                 394,328           7.8%    164,000    Cupertino, California
4                 324,162          12.7%    400,000    Minnetonka, Minnesota
..                    ...            ...        ...                      ...
95                 46,298          10.6%     71,100     Richfield, Minnesota
96                 46,159           0.5%     34,300  New York City, New York
97                 44,955          82.5%     92,795        Chicago, Illinois
98                 44,915          14.5%    130,000   Waltham, Massachusetts
99                 44,200          31.7%     51,000    San Diego, California

[100 rows x 7 columns]

In [50]:
pd.DataFrame(df)

,Rank,Name,Industry,Revenue (USD millions),Revenue growth,Employees,Headquarters
0,1,Walmart,Retail,"611,289",6.7%,"2,100,000","Bentonville, Arkansas"
1,2,Amazon,Retail and cloud computing,"513,983",9.4%,"1,540,000","Seattle, Washington"
2,3,ExxonMobil,Petroleum industry,"413,680",44.8%,"62,000","Spring, Texas"
3,4,Apple,Electronics industry,"394,328",7.8%,"164,000","Cupertino, California"
4,5,UnitedHealth Group,Healthcare,"324,162",12.7%,"400,000","Minnetonka, Minnesota"
...,...,...,...,...,...,...,...
95,96,Best Buy,Retail,"46,298",10.6%,"71,100","Richfield, Minnesota"
96,97,Bristol-Myers Squibb,Pharmaceutical industry,"46,159",0.5%,"34,300","New York City, New York"
97,98,United Airlines,Airline,"44,955",82.5%,"92,795","Chicago, Illinois"
98,99,Thermo Fisher Scientific,Laboratory instruments,"44,915",14.5%,"130,000","Waltham, Massachusetts"
99,100,Qualcomm,Technology,"44,200",31.7%,"51,000","San Diego, California"

In [52]:
df.to_csv(r'D:\Data Science\webscarping companies data project\companies revenue.csv',index=False)